# ============================
# Site Variables
# ============================

# Copyright Wizardry
first_publication_year: 2022

# URL Root (used in URIs) - THESE SHOULD NOT END IN "/"
baseurl: /site-testing
repourl: https://github.com/BellCubeDev/site-testing
fullurl: https://bellcubedev.github.io/site-testing
mainurl: https://bellcubedev.github.io

# ============================
# SEO
# ============================
title: BellCubeDev.GitHub.IO
tagline: The open-source site for BellCube and the home of a decent hobbyist programmer
author:
  name: BellCube
  picture: /site-testing/assets/site/images/icon.png
  url: https://bellcubedev.github.io
logo: /site-testing/assets/site/images/icon.png
defaults:
  - scope:
      path: "assets/site/images/SVGs"
    values:
      layout: compress_html

social:
  name: BellCube's Site
description: >
  The website for BellCube, a hobbyist video game modder and web developer. The site hosts documentation, tools, and project updates—and possibly the occasional blog post. Best of all, it's all open-source!

  BellCube can be found on GitHub and Nexus Mods as well.


# ============================
# Actual Jekyll Configuration
# ============================
open_url: false

livereload_min_delay: 100
livereload: false

# Where things are
source      : .

# Handling Reading
safe               : true
markdown_ext       : "mkd" # Stops Jekyll from processing .md so I can stop worrying about it
strict_front_matter: true

# Filtering Content
show_drafts: false

# Plugins
whitelist:
  - jekyll-redirect-from
  - jekyll-brotli
  # Default Plugins from GitHub Pages
  - jekyll-seo-tag
  - jekyll-coffeescript
  - jekyll-commonmark-ghpages
  - jekyll-gist
  - jekyll-github-metadata
  - jekyll-paginate
  - jekyll-relative-links
  - jekyll-readme-index
  - jekyll-default-layout
  - jekyll-titles-from-headings

plugins:
  - jekyll-redirect-from
  - jekyll-brotli
  # Default Plugins from GitHub Pages
  - jekyll-seo-tag
  - jekyll-coffeescript
  - jekyll-commonmark-ghpages
  - jekyll-gist
  - jekyll-github-metadata
  - jekyll-paginate
  - jekyll-relative-links
  - jekyll-readme-index
  - jekyll-default-layout
  - jekyll-titles-from-headings

# Conversion
lsi : false

# Outputting
timezone: America/New_York
verbose : true

liquid:
  error_mode      : warn
  strict_filters  : true
  strict_variables: false

# Compress CSS
sass:
  sass_dir: /assets/site/
  sourcemap: always
  style: compressed


# Compress HTML Settings
compress_html:
  comments: ["<!--", "-->"]
  startings: []
