source 'https://rubygems.org'

gem 'jekyll'

# Windows
gem 'github-pages'
gem 'wdm' if Gem.win_platform?

# Custom Plugins
gem "webrick", "~> 1.7"
gem 'tzinfo-data'
gem 'jekyll-brotli'

# GitHub Defaults
gem 'jekyll-seo-tag'
gem 'jekyll-coffeescript'
gem 'jekyll-commonmark-ghpages'
gem 'jekyll-gist'
gem 'jekyll-github-metadata'
gem 'jekyll-paginate'
gem 'jekyll-relative-links'
gem 'jekyll-optional-front-matter'
gem 'jekyll-readme-index'
gem 'jekyll-default-layout'
gem 'jekyll-titles-from-headings'
